// The following is entirely generated by Claude code to demonstrate the
// potential of our simulation engine.

#include "config.h"
#include "extension_types.h"
#include <math.h>
#include <stdbool.h>
#include <stdlib.h>

// ---------------------------------------------------------------------------
// A solid maroon "?" -- the same 3D rounded-rod glyph as question_cobra.c, but
// stripped of the heap, the rise/fall choreography and the stripes. It simply
// stands fully formed and spins continuously about its vertical axis. Loops
// forever.
//
// Cells never move, so the spin is FAKED. Each cell keeps its own `counter`
// and bumps it by 1 every step; the engine updates every cell exactly once per
// step, so all counters stay in lockstep -- a shared frame clock without a
// (thread-racy) global. From that clock we derive a rotation angle and, instead
// of rotating the shape, we rotate the CELL'S query point by the opposite angle
// and test it against the fixed "?" geometry (inverse-transform sampling). All
// cells sample the same angle, so the glyph appears to turn as one rigid body.
//
// The "?" is a TUBE: its centreline is a curve in 3D (hook arc + stem in the
// mid-depth plane, plus a separate dot sphere) and a cell is "ink" if its 3D
// distance to that centreline is within the tube radius. NOTE: the rod only
// looks round, and the spin only looks circular, on a roughly cubic grid (e.g.
// -d 70x70x70), since x/y/z normalise by width/height/depth separately.
// ---------------------------------------------------------------------------

// --- Rotation --------------------------------------------------------------
// Angle advanced per simulation step. 2*pi / 120 gives one full turn every
// ~120 steps; raise for a faster spin, lower for slower.
#define ROT_SPEED (float)(2.0 * M_PI / 120.0)
#define AXIS_X 0.5f // the vertical spin axis passes through the grid centre
#define AXIS_Z 0.5f // (x,z) centre; y is up and is left untouched by the spin
#define CLOCKWISE 1
#define COUNTERCLOCKWISE -1

// --- Geometry of the "?" centreline ----------------------------------------
// The hook + stem live in the mid-depth plane; the tube is a constant radius
// around that curve.
#define DEG (float)(M_PI / 180.0) // degrees -> radians helper

#define GLYPH_Z 0.5f      // depth plane the centreline sits in
#define TUBE_RADIUS 0.06f // rod radius: cell is ink within this of centreline

// Hook: a near-circular arc forming the top loop of the "?".
#define HOOK_CX 0.5f
#define HOOK_CY 0.70f
#define HOOK_R 0.18f
#define HOOK_A0 (-55.0f * DEG) // lower-right end (where the stem attaches)
#define HOOK_A1 (200.0f * DEG) // sweeps CCW up over the top to the lower-left

// Stem: a short diagonal from the hook's end into the centre, then straight
// down. Two line segments sharing the mid point.
#define STEM_TOP_X 0.603f // == hook end point at HOOK_A0
#define STEM_TOP_Y 0.553f
#define STEM_MID_X 0.5f
#define STEM_MID_Y 0.47f
#define STEM_BOT_X 0.5f
#define STEM_BOT_Y 0.40f

// Dot: a little ball under the gap.
#define DOT_CX 0.5f
#define DOT_CY 0.24f
#define DOT_R 0.06f

// One cell of the simulation. The whole glyph is computed live each frame, so a
// cell only needs to remember the shared frame clock used to drive the spin.
typedef struct {
  uint32_t counter; // shared frame clock (every cell increments in sync)
} Cell;

const size_t cell_size = sizeof(Cell);

static uint grid_width;
static uint grid_height;
static uint grid_depth;

void dims_init(uint width, uint height, uint depth) {
  grid_width = width;
  grid_height = height;
  grid_depth = depth;
}

// Distance from point (px,py) to the line segment a->b.
static float dist_segment(float px, float py, float ax, float ay, float bx,
                          float by) {
  float abx = bx - ax, aby = by - ay;
  float apx = px - ax, apy = py - ay;
  float ab2 = abx * abx + aby * aby;
  // project ap onto ab, clamped to the segment [0,1]
  float t = (ab2 > 0.0f) ? (apx * abx + apy * aby) / ab2 : 0.0f;
  if (t < 0.0f)
    t = 0.0f;
  if (t > 1.0f)
    t = 1.0f;
  float cx = ax + t * abx, cy = ay + t * aby;
  return hypotf(px - cx, py - cy);
}

// Distance from point (px,py) to a circular arc of radius r about (cx,cy),
// sweeping CCW from angle a0 to a1.
static float dist_arc(float px, float py, float cx, float cy, float r, float a0,
                      float a1) {
  float dx = px - cx, dy = py - cy;
  float ang = atan2f(dy, dx); // in [-pi, pi]
  // bring ang into [a0, a0 + 2pi) so we can test it against the sweep
  while (ang < a0)
    ang += 2.0f * (float)M_PI;
  if (ang <= a1) {
    // inside the angular sweep: distance is just radial offset from the ring
    return fabsf(hypotf(dx, dy) - r);
  }
  // outside the sweep: nearest point is one of the two arc endpoints
  float e0x = cx + r * cosf(a0), e0y = cy + r * sinf(a0);
  float e1x = cx + r * cosf(a1), e1y = cy + r * sinf(a1);
  float d0 = hypotf(px - e0x, py - e0y);
  float d1 = hypotf(px - e1x, py - e1y);
  return (d0 < d1) ? d0 : d1;
}

// Shortest in-plane distance from (x,y) to the hook+stem centreline.
static float dist_to_centreline_2d(float x, float y) {
  float d = dist_arc(x, y, HOOK_CX, HOOK_CY, HOOK_R, HOOK_A0, HOOK_A1);
  d = fminf(d, dist_segment(x, y, STEM_TOP_X, STEM_TOP_Y, STEM_MID_X, STEM_MID_Y));
  d = fminf(d, dist_segment(x, y, STEM_MID_X, STEM_MID_Y, STEM_BOT_X, STEM_BOT_Y));
  return d;
}

// Is (x,y,z) inside the rod tube (hook + stem only, NOT the dot)?
static bool is_rod_point(float x, float y, float z) {
  float dz = z - GLYPH_Z; // how far this cell is from the glyph's depth plane
  return hypotf(dist_to_centreline_2d(x, y), dz) < TUBE_RADIUS;
}

// Is (x,y,z) inside the dot's sphere?
static bool is_dot_point(float x, float y, float z) {
  float dz = z - GLYPH_Z;
  float dd = sqrtf((x - DOT_CX) * (x - DOT_CX) + (y - DOT_CY) * (y - DOT_CY) +
                   dz * dz);
  return dd < DOT_R;
}

// Paint the cell solid maroon (128, 0, 0), fully opaque.
static void paint_maroon(RenderInfo *r) {
  r->red = 0x80;
  r->green = 0x00;
  r->blue = 0x00;
  r->alpha = MAX_RGBA_VAL;
}

// Set the cell's render colour for the current frame, given its position.
static void render(const Cell *cell, RenderInfo *r, float x, float y, float z) {
  // Spin: rotate this cell's (x,z) by -theta about the vertical axis, then test
  // against the STATIC glyph. Rotating the sample point backwards is equivalent
  // to rotating the shape forwards (inverse-transform sampling). y is up, so it
  // is left untouched and the spin stays purely about the vertical axis.
  float theta = (float)cell->counter * ROT_SPEED * COUNTERCLOCKWISE;
  float c = cosf(theta), s = sinf(theta);
  float dx = x - AXIS_X, dz = z - AXIS_Z;
  // standard 2D rotation matrix applied to the (dx,dz) offset from the axis
  float rx = AXIS_X + dx * c - dz * s;
  float rz = AXIS_Z + dx * s + dz * c;

  // ink if the un-rotated point lands inside the rod tube or the dot sphere
  if (is_rod_point(rx, y, rz) || is_dot_point(rx, y, rz)) {
    paint_maroon(r);
    return;
  }

  // empty air (alpha 0 == not drawn, so no --transparency flag needed)
  r->red = r->green = r->blue = 0;
  r->alpha = 0;
}

void cell_init(void *cell_to_update, RenderInfo *renderer_state, uint col,
               uint row, uint slice) {
  Cell *cell = cell_to_update;
  cell->counter = 0;

  // map this cell to a normalised (x,y,z); y is up so the glyph sits upright.
  // (if it ever renders upside-down, flip to: 1.0f - (row + 0.5f) / height)
  float x = ((float)col + 0.5f) / (float)grid_width;
  float y = ((float)row + 0.5f) / (float)grid_height;
  float z = ((float)slice + 0.5f) / (float)grid_depth;

  render(cell, renderer_state, x, y, z);
}

void cell_update(void *cell_to_update, RenderInfo *renderer_state,
                 const void *curr_sim_state, uint col, uint row, uint slice) {
  Cell *next = cell_to_update;
  const Cell *grid = curr_sim_state;

  // the glyph is computed live, so just carry the cell forward and advance its
  // frame clock by one step (this is what drives the spin).
  Cell curr = grid[INDEX(col, row, slice, grid_width, grid_height)];
  *next = curr;
  next->counter = curr.counter + 1;

  float x = ((float)col + 0.5f) / (float)grid_width;
  float y = ((float)row + 0.5f) / (float)grid_height;
  float z = ((float)slice + 0.5f) / (float)grid_depth;
  render(next, renderer_state, x, y, z);
}
