// The following is entirely generated by Claude code to demonstrate the
// potential of our simulation engine.

#include "config.h"
#include "extension_types.h"
#include <math.h>
#include <stdbool.h>
#include <stdlib.h>

// ---------------------------------------------------------------------------
// A cobra-striped "?" (a genuine 3D rounded rod, green with yellow bands) rears
// up out of a scattered heap of green/yellow bricks like a charmer's cobra --
// swaying side to side as it rises, then settling into a clean "?" at the top,
// holding for a delay, and swaying back down. The heap itself dissolves into
// the rod, so the mound BECOMES the "?". Loops forever.
//
// Key idea: cell_update receives no global frame number, so each cell keeps
// its own `counter` and bumps it by 1 every step. The engine updates every
// cell exactly once per step, so all counters stay in lockstep -- this acts
// as a shared frame clock without a (thread-racy) global variable.
//
// Cells never move, so every motion is faked from a fixed grid:
//   * the rear-up: the body (hook + stem) grows as ONE continuous strand along
//     its path, from the base up the stem and around the hook to the head tip.
//   * the cobra sway: rod membership is tested LIVE each frame against a
//     swaying pose (we undo a time- and height-dependent horizontal sway and
//     test the cheap analytic "?" shape). The sway is anchored at the base,
//     biggest at the head, and decays to zero at full rise for a clean "?".
//   * the heap: bricks are scattered by a height-dependent probability and
//     dissolve as the rise progresses, so at full rise the heap is gone.
//   * the dot: NOT part of the rising body. It assembles last, cell by cell,
//     over the final stretch of the rise -- as if formed from the cubes left
//     over once the body has reared up -- completing the "?".
//
// The "?" is a TUBE: its centreline is a curve in 3D (hook arc + stem in the
// mid-depth plane, plus a separate dot sphere) and a cell is "ink" if its 3D
// distance to that centreline is within the tube radius. NOTE: the rod only
// looks round on a roughly cubic grid (e.g. -d 70x70x70), since x/y/z normalise
// by width/height/depth separately.
// ---------------------------------------------------------------------------

// --- Animation timing (all measured in simulation steps) -------------------
// Reveal progress p goes 0 (hidden in heap) -> 1 (fully risen) -> 0:
//   rise (rear up, swaying) -> hold (clean "?") -> fall (sway back) -> rest.
#define RISE_END 90u  // steps 0..90:    cobra rears up out of the heap
#define HOLD_END 180u // steps 90..180:  hold as a clean "?" (the delay)
#define FALL_END 270u // steps 180..270: sways back down into the heap
#define PERIOD 310u   // steps 270..310: rest as just the heap, then loop

// --- The cobra sway --------------------------------------------------------
#define SWAY_AMP 0.09f   // max horizontal sway (normalised), at the head
#define SWAY_FREQ 8.0f   // spatial: how many bends along the body's height
#define SWAY_SPEED 0.15f // temporal: how fast it dances, per step
#define SWAY_BASE 0.18f  // height the sway is anchored at (in the heap)

// --- The dot ---------------------------------------------------------------
#define DOT_FORM 0.90f // rise level past which the dot starts assembling

// --- The heap of bricks ----------------------------------------------------
// A low mound peaking in the centre. Brick density is dense below the local
// surface and frays to nothing just above it, giving a scattered dusty top.
#define HEAP_FLOOR 0.05f  // surface height at the rim (thin sprinkle)
#define HEAP_MOUND 0.10f  // extra surface height at the centre (the peak)
#define HEAP_RADIUS 0.6f  // how far the mound spreads from the centre
#define HEAP_FRINGE 0.05f // vertical band over which the top frays out
#define HEAP_CORE 0.85f   // fill fraction of the core (<1 leaves brick gaps)
#define HEAP_CLEAR 0.95f  // rise fraction by which the heap is fully gone

// --- Geometry of the "?" centreline ----------------------------------------
// The hook + stem live in the mid-depth plane; the tube is a constant radius
// around that curve. The whole glyph spans up to GLYPH_TOP in height.
#define DEG (float)(M_PI / 180.0) // degrees -> radians helper

#define GLYPH_Z 0.5f      // depth plane the centreline sits in
#define TUBE_RADIUS 0.06f // rod radius: cell is ink within this of centreline
#define GLYPH_TOP 0.95f   // top of the hook (used to scale the sway envelope)

// Hook: a near-circular arc forming the top loop of the "?".
#define HOOK_CX 0.5f
#define HOOK_CY 0.70f
#define HOOK_R 0.18f
#define HOOK_A0 (-55.0f * DEG) // lower-right end (where the stem attaches)
#define HOOK_A1 (200.0f * DEG) // sweeps CCW up over the top to the lower-left

// Stem: a short diagonal from the hook's end into the centre, then straight
// down. Two line segments sharing the mid point.
#define STEM_TOP_X 0.603f // == hook end point at HOOK_A0
#define STEM_TOP_Y 0.553f
#define STEM_MID_X 0.5f
#define STEM_MID_Y 0.47f
#define STEM_BOT_X 0.5f
#define STEM_BOT_Y 0.40f

// Dot: a little ball under the gap.
#define DOT_CX 0.5f
#define DOT_CY 0.24f
#define DOT_R 0.06f

// --- Stripes ---------------------------------------------------------------
#define STRIPE_WIDTH 0.07f // normalised thickness of each cobra band

// One cell of the simulation. The rod is computed live each frame, so a cell
// only needs to remember the (static) heap brick it may belong to, plus a
// random value used to stagger the heap dissolve and the dot's assembly.
typedef struct {
  uint32_t counter;     // shared frame clock (every cell increments in sync)
  uint8_t is_brick;     // 1 if this cell is part of the heap
  uint8_t brick_yellow; // 1 = yellow brick, 0 = green brick
  uint8_t rnd;          // per-cell random 0..255 (dissolve / assembly order)
} Cell;

const size_t cell_size = sizeof(Cell);

static uint grid_width;
static uint grid_height;
static uint grid_depth;

static inline float rand_float(void) { return (float)rand() / (float)RAND_MAX; }

void dims_init(uint width, uint height, uint depth) {
  grid_width = width;
  grid_height = height;
  grid_depth = depth;
}

// Distance from point (px,py) to the line segment a->b.
static float dist_segment(float px, float py, float ax, float ay, float bx,
                          float by) {
  float abx = bx - ax, aby = by - ay;
  float apx = px - ax, apy = py - ay;
  float ab2 = abx * abx + aby * aby;
  // project ap onto ab, clamped to the segment [0,1]
  float t = (ab2 > 0.0f) ? (apx * abx + apy * aby) / ab2 : 0.0f;
  if (t < 0.0f)
    t = 0.0f;
  if (t > 1.0f)
    t = 1.0f;
  float cx = ax + t * abx, cy = ay + t * aby;
  return hypotf(px - cx, py - cy);
}

// Distance from point (px,py) to a circular arc of radius r about (cx,cy),
// sweeping CCW from angle a0 to a1.
static float dist_arc(float px, float py, float cx, float cy, float r, float a0,
                      float a1) {
  float dx = px - cx, dy = py - cy;
  float ang = atan2f(dy, dx); // in [-pi, pi]
  // bring ang into [a0, a0 + 2pi) so we can test it against the sweep
  while (ang < a0)
    ang += 2.0f * (float)M_PI;
  if (ang <= a1) {
    // inside the angular sweep: distance is just radial offset from the ring
    return fabsf(hypotf(dx, dy) - r);
  }
  // outside the sweep: nearest point is one of the two arc endpoints
  float e0x = cx + r * cosf(a0), e0y = cy + r * sinf(a0);
  float e1x = cx + r * cosf(a1), e1y = cy + r * sinf(a1);
  float d0 = hypotf(px - e0x, py - e0y);
  float d1 = hypotf(px - e1x, py - e1y);
  return (d0 < d1) ? d0 : d1;
}

// Shortest in-plane distance from (x,y) to the hook+stem centreline.
static float dist_to_centreline_2d(float x, float y) {
  float d = dist_arc(x, y, HOOK_CX, HOOK_CY, HOOK_R, HOOK_A0, HOOK_A1);
  d = fminf(d,
            dist_segment(x, y, STEM_TOP_X, STEM_TOP_Y, STEM_MID_X, STEM_MID_Y));
  d = fminf(d,
            dist_segment(x, y, STEM_MID_X, STEM_MID_Y, STEM_BOT_X, STEM_BOT_Y));
  return d;
}

// Is (x,y,z) inside the rod tube (hook + stem only, NOT the dot)?
static bool is_rod_point(float x, float y, float z) {
  float dz = z - GLYPH_Z; // how far this cell is from the glyph's depth plane
  return hypotf(dist_to_centreline_2d(x, y), dz) < TUBE_RADIUS;
}

// Is (x,y,z) inside the dot's sphere?
static bool is_dot_point(float x, float y, float z) {
  float dz = z - GLYPH_Z;
  float dd = sqrtf((x - DOT_CX) * (x - DOT_CX) + (y - DOT_CY) * (y - DOT_CY) +
                   dz * dz);
  return dd < DOT_R;
}

// Distance from (px,py) to segment a->b, also reporting the clamped projection
// parameter t in [0,1] (how far along the segment the nearest point is).
static float seg_dist_t(float px, float py, float ax, float ay, float bx,
                        float by, float *t_out) {
  float abx = bx - ax, aby = by - ay;
  float apx = px - ax, apy = py - ay;
  float ab2 = abx * abx + aby * aby;
  float t = (ab2 > 0.0f) ? (apx * abx + apy * aby) / ab2 : 0.0f;
  if (t < 0.0f)
    t = 0.0f;
  if (t > 1.0f)
    t = 1.0f;
  *t_out = t;
  return hypotf(px - (ax + t * abx), py - (ay + t * aby));
}

// Position of (x,y) ALONG the rod's centreline, as a fraction [0,1] of total
// arc length: 0 at the stem base, up the stem, around the hook, 1 at the head
// tip. This is what makes the rod grow as one continuous strand.
static float path_position(float x, float y) {
  // arc lengths of the three pieces, in path order
  float l1 = hypotf(STEM_MID_X - STEM_BOT_X, STEM_MID_Y - STEM_BOT_Y);
  float l2 = hypotf(STEM_TOP_X - STEM_MID_X, STEM_TOP_Y - STEM_MID_Y);
  float l3 = HOOK_R * (HOOK_A1 - HOOK_A0);
  float total = l1 + l2 + l3;

  float best_d = 1e9f, best_pos = 0.0f, t;

  // stem, segment 1 (base -> mid)
  float d =
      seg_dist_t(x, y, STEM_BOT_X, STEM_BOT_Y, STEM_MID_X, STEM_MID_Y, &t);
  if (d < best_d) {
    best_d = d;
    best_pos = t * l1;
  }

  // stem, segment 2 (mid -> top)
  d = seg_dist_t(x, y, STEM_MID_X, STEM_MID_Y, STEM_TOP_X, STEM_TOP_Y, &t);
  if (d < best_d) {
    best_d = d;
    best_pos = l1 + t * l2;
  }

  // hook arc (A0 -> A1)
  float dx = x - HOOK_CX, dy = y - HOOK_CY;
  float ang = atan2f(dy, dx);
  while (ang < HOOK_A0)
    ang += 2.0f * (float)M_PI;
  float frac, dh;
  if (ang <= HOOK_A1) {
    frac = (ang - HOOK_A0) / (HOOK_A1 - HOOK_A0);
    dh = fabsf(hypotf(dx, dy) - HOOK_R);
  } else {
    // off the sweep: clamp to whichever arc endpoint is nearer
    float e0x = HOOK_CX + HOOK_R * cosf(HOOK_A0);
    float e0y = HOOK_CY + HOOK_R * sinf(HOOK_A0);
    float e1x = HOOK_CX + HOOK_R * cosf(HOOK_A1);
    float e1y = HOOK_CY + HOOK_R * sinf(HOOK_A1);
    float d0 = hypotf(x - e0x, y - e0y);
    float d1 = hypotf(x - e1x, y - e1y);
    frac = (d0 < d1) ? 0.0f : 1.0f;
    dh = fminf(d0, d1);
  }
  if (dh < best_d) {
    best_pos = l1 + l2 + frac * l3;
  }

  return best_pos / total;
}

// Horizontal sway of the cobra's body at height y and time t, given rise p.
// Anchored (zero) at the base, largest at the head, and fades out as p -> 1.
static float cobra_sway(float y, uint32_t t, float p) {
  float hf = (y - SWAY_BASE) / (GLYPH_TOP - SWAY_BASE); // 0 at base, 1 at head
  if (hf < 0.0f)
    hf = 0.0f;
  if (hf > 1.0f)
    hf = 1.0f;
  return SWAY_AMP * (1.0f - p) * hf *
         sinf((float)t * SWAY_SPEED + y * SWAY_FREQ);
}

// Fraction of bricks kept at (x,y,z): a centred mound, dense below its local
// surface and fraying to nothing just above it.
static float heap_density(float x, float y, float z) {
  float dx = x - 0.5f, dz = z - 0.5f;
  float r = sqrtf(dx * dx + dz * dz); // 0 at centre column, grows outward

  float mound = 1.0f - r / HEAP_RADIUS;
  if (mound < 0.0f)
    mound = 0.0f;
  float surface = HEAP_FLOOR + HEAP_MOUND * mound;

  if (y >= surface)
    return 0.0f; // above the heap surface: empty air
  float depth = surface - y;
  // fray the top HEAP_FRINGE band, solid (HEAP_CORE) below that
  return (depth < HEAP_FRINGE) ? HEAP_CORE * (depth / HEAP_FRINGE) : HEAP_CORE;
}

// Reveal progress in [0,1]: 0 = hidden in heap, 1 = fully risen. Trapezoid.
static float reveal_amount(uint32_t counter) {
  uint32_t t = counter % PERIOD;
  if (t < RISE_END)
    return (float)t / (float)RISE_END; // rearing up out of the heap
  if (t < HOLD_END)
    return 1.0f; // hold as a clean "?" (the delay before it falls)
  if (t < FALL_END)
    return 1.0f -
           (float)(t - HOLD_END) / (float)(FALL_END - HOLD_END); // swaying back
  return 0.0f;                                                   // rest in heap
}

// Cobra band colour at a point on the body: 1 = yellow band, 0 = green base.
static uint8_t stripe_yellow(float x, float y, float z) {
  // alternating bands along a 3D diagonal, so they wrap around the rod
  return (uint8_t)((int)floorf((x + y + z) / STRIPE_WIDTH) & 1);
}

// Paint one of the two cobra colours: green base, or a yellow band.
static void paint_scale(RenderInfo *r, uint8_t yellow) {
  r->red = yellow ? 0xE2 : 0x38; // yellow = (255,255,0), green = (0,255,0)
  r->green = yellow ? 0xDE : 0x6C;
  r->blue = yellow ? 0x84 : 0x0B;
  r->alpha = MAX_RGBA_VAL;
}

// Set the cell's render colour for the current frame, given its position.
static void render(const Cell *cell, RenderInfo *r, float x, float y, float z) {
  float p = reveal_amount(cell->counter);

  // --- the dancing cobra body (hook + stem), grown live as one strand ---
  // a cell is rod once the rise p has reached its position ALONG the path.
  // (p > 0, so nothing shows at rest.)
  if (p > 0.0f) {
    float sx = x - cobra_sway(y, cell->counter, p); // undo the sway
    if (is_rod_point(sx, y, z) && path_position(sx, y) <= p) {
      paint_scale(r, stripe_yellow(sx, y, z));
      return;
    }
  }

  // --- the dot: formed last, assembling cell by cell over the final stretch
  // of the rise, as if built from the cubes left once the body has reared up.
  if (is_dot_point(x, y, z)) {
    float thr = DOT_FORM + (1.0f - DOT_FORM) * ((float)cell->rnd / 255.0f);
    if (p >= thr) {
      paint_scale(r, stripe_yellow(x, y, z));
      return;
    }
  }

  // --- the dissolving heap ---
  // a brick vanishes once the rise passes its threshold. thresholds are packed
  // into the first HEAP_CLEAR of the rise, so the heap is gone well before the
  // body finishes rearing up and the mound has become the "?".
  if (cell->is_brick) {
    float thr = ((float)cell->rnd + 0.5f) / 256.0f * HEAP_CLEAR;
    if (p < thr) {
      paint_scale(r, cell->brick_yellow);
      return;
    }
  }

  // empty air (alpha 0 == not drawn, so no --transparency flag needed)
  r->red = r->green = r->blue = 0;
  r->alpha = 0;
}

void cell_init(void *cell_to_update, RenderInfo *renderer_state, uint col,
               uint row, uint slice) {
  Cell *cell = cell_to_update;
  cell->counter = 0;
  cell->rnd = (uint8_t)(rand() & 0xFF); // staggers heap dissolve & dot assembly

  // map this cell to a normalised (x,y,z); y is up so the glyph sits upright.
  // (if it ever renders upside-down, flip to: 1.0f - (row + 0.5f) / height)
  float x = ((float)col + 0.5f) / (float)grid_width;
  float y = ((float)row + 0.5f) / (float)grid_height;
  float z = ((float)slice + 0.5f) / (float)grid_depth;

  // only the heap is stored; the rod and dot are computed live in render().
  if (rand_float() < heap_density(x, y, z)) {
    cell->is_brick = 1;
    cell->brick_yellow = (uint8_t)(rand() & 1); // each brick green or yellow
  } else {
    cell->is_brick = 0;
    cell->brick_yellow = 0;
  }

  render(cell, renderer_state, x, y, z);
}

void cell_update(void *cell_to_update, RenderInfo *renderer_state,
                 const void *curr_sim_state, uint col, uint row, uint slice) {
  Cell *next = cell_to_update;
  const Cell *grid = curr_sim_state;

  // the static fields never change, so carry the current cell forward and
  // just advance its frame clock by one step.
  Cell curr = grid[INDEX(col, row, slice, grid_width, grid_height)];
  *next = curr;
  next->counter = curr.counter + 1;

  float x = ((float)col + 0.5f) / (float)grid_width;
  float y = ((float)row + 0.5f) / (float)grid_height;
  float z = ((float)slice + 0.5f) / (float)grid_depth;
  render(next, renderer_state, x, y, z);
}
