name: CI

on:
  # push:
  #   branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  MAKEFILE_DIR: "."
  SCRIPTS_DIR: "./scripts"

jobs:
  lint-format-build:
    runs-on: ubuntu-latest
    steps:
    # clone the repo 
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: cd ${{ env.SCRIPTS_DIR }} && bash install_dependencies.sh
    - name: Linter
      run: make -C ${{ env.MAKEFILE_DIR }} lint
    - name: Formatter
      run: make -C ${{ env.MAKEFILE_DIR }} format
    - name: Build
      run: make -C ${{ env.MAKEFILE_DIR }} build
